### ISSUE TITLE
specials in num_fmt = cause errors

### ISSUE THREAD

**Issue by npelikan** [ardata-fr/mschart#11]
In attempting to format chart axes and labels as percentages, I passed the excel syntax for 2-decimal place percentages (`0.00%`) to num_fmt. However this causes the error 
```
Error in sprintf(str_, dir_, x$options$grouping, x$options$vary_colors,  : 
  invalid format '%" s'; use format %f, %e, %g or %a for numeric objects
```

To appear. Escaping the special (`"\\%"`) has no effect, and returns the same error.

**Comment by davidgohel** [comment]
I improved documentation. You need to use `0.00%%` (because it is used with `sprintf`).

```
sc_01 <- ms_scatterchart(data = mtcars, x = "disp", y = "drat")
sc_01 <- chart_ax_y(sc_01, num_fmt = "0.0%%")
print(sc_01, preview = TRUE)
```

I don't know yet if it is possible to check `num_fmt` validity...

**Comment by npelikan** [comment]
One suggestion on checking num_fmt validity -- you could wrap the sprintf in `try()` and return a more informative error if the class of the return is 'try-error'
