### ISSUE TITLE
ms_linechart does not work with non-numeric x axis

### ISSUE THREAD

**Issue by npelikan** [ardata-fr/mschart#12]
Hi David,

I was attempting to create a lineplot with the x axis defined as an ordered factor of month names -- minimal example: 
```
td <- data.frame(x = factor(sample(c("June", "July", "August"), 20, replace = T), ordered = T), y = runif(20), group = sample(1:3, 20, replace = T))
pp <- ms_linechart(td, x = 'x', y = 'y', group = 'group')
print(pp, preview = T)
```
However this does not work, and rather than failing fast it instead returns a corrupted pptx file. Character vectors exhibit the same behavior.

**Comment by npelikan** [comment]
Because special date formatting and linecharts of non-numeric based continuous data are an extremely common practice, I think the most desirable behavior would be for `ms_linechart()` to support character vector/ordered factors on the x axis.

**Comment by npelikan** [comment]
Because special date formatting and linecharts of non-numeric based 'continuous' data are an extremely common practice, I think the most desirable behavior would be for ms_linechart() to support character vector/ordered factors on the x axis.

**Comment by davidgohel** [comment]
Hi 

I could not reproduce the *corrupted pptx file* but could help on the non numeric x-axis. 

Can you have a try?

**Comment by npelikan** [comment]
Hi David -- Looks like it works now. Thank you so much!
