### ISSUE TITLE
Error plotting scatter plots with special characters ("&") in the data

### ISSUE THREAD

**Issue by martinctc** [ardata-fr/mschart#15]
"Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  : 
  EntityRef: expecting ';' [23]"

This error seems to appear whenever certain special characters appear in the data. In the following example, I used the character string "&" as the column name of the data, and produced the error: 

`tibble("B&O"=1:10,"Bose"=sample(5:20,10,replace=TRUE)) %>%`
`  ms_scatterchart(x="B&O",y="Bose") -> chart.xx`
`xx <- read_pptx()`
`layout_summary(xx)`
`xx <- add_slide(xx,layout="Title and Content",master="Office Theme")`
`xx <- ph_with_chart(xx,chart=chart.xx)`

This is a minor issue that I can get around, but thought I'd report this anyway. Love this package, there is definitely a lot of potential for this because people continue to ask for PowerPoint reports due to its flexibility for non-technical users to make subsequent changes to the data. Also would look forward to data label editing functionalities (font size, etc.) in the future, if possible...

**Comment by davidgohel** [comment]
Hi,

I think you have the cran version, the dev version on github is supposed to manage that correctly
