### ISSUE TITLE
chart_data_labels output font does not conform to chart_theme

### ISSUE THREAD

**Issue by npelikan** [ardata-fr/mschart#18]
It seems that, when reformatted using `num_fmt = `, data labels emplaced by chart_data_labels do not conform to the presentation theme, specifically regarding font. It seems that no matter the input from chart_theme(), the output font for data labels is always Calibri.

See #16 for an MWE that demonstrates the issue.

How can I ensure that data labels take the correct font?

**Comment by davidgohel** [comment]
There is nothing to be conform to as unfortunately there is no option for formatting data labels in `chart_theme`. 

> How can I ensure that data labels take the correct font?

Change the ppt theme?

Please provide a `sessionInfo()` and a reproducible code next time.

**Comment by davidgohel** [comment]
I added `legend_text` argument in `chart_theme()`.
