### ISSUE TITLE
change font size in legends

### ISSUE THREAD

**Issue by mshors** [ardata-fr/mschart#19]
Hello, Great work.  I was hoping there was a way to change the font size when a legend is added to a chart.  Also, a way of changing the label font on the chart as well.

Thanks

**Comment by davidgohel** [comment]
Hello mshors,

Please provide a `sessionInfo()` and a reproducible code if you think there is an issue.

From what I understand, you need to change legend font size: see `?set_theme` to open the relevant function help file, you will see all available options to change fonts. Note that there is no option for legend font (it use the theme default one).

**Comment by kubabartak** [comment]
Hi! 
Thanks for the awesome package. 
Is it possible to change the size of data labels in a bar plot?
Labels that are set with:
`chart_data_labels(my_barchart, position = 'outEnd', show_val = TRUE)`

 I can't find such function in set_theme.  Yet, the labels are big and overlay with each other.

**Comment by davidgohel** [comment]
Hi,

That is not implemented. I will implement it next time I will work on the package.

PS: Please open a new issue to make sure I will remember that, this one is about font setting in legends and this is now available.
