### ISSUE TITLE
Change the size of data labels

### ISSUE THREAD

**Issue by kubabartak** [ardata-fr/mschart#20]
Hi!
Thanks for the awesome package.
It would be useful to be able to change the size of data labels in a bar plot.
Labels that are set with:
chart_data_labels(my_barchart, position = 'outEnd', show_val = TRUE)

I can't find such function in set_theme. Yet, the labels are big and overlay with each other.

**Comment by sfr** [comment]
Hi. When you'll be implementing it, can it have an independent color selection for each group. It would help readability in cases like this:
![image](https://user-images.githubusercontent.com/2040557/38867442-5a44984e-4244-11e8-8ff5-71b42dc02bfd.png)

**Comment by davidgohel** [comment]
Hi,

You can test the following with the new version on Github. 

I have implemented a new function named `chart_labels_text`, it can be used to associate font settings with series labels:


```
library(officer)
library(mschart)

fp_text_settings <- list(
  serie1 = fp_text(font.size = 7, color = "red"),
  serie2 = fp_text(font.size = 0, color = "purple"),
  serie3 = fp_text(font.size = 19, color = "wheat")
)

barchart <- ms_barchart(
  data = browser_data,
  x = "browser", y = "value", group = "serie")
barchart <- chart_data_labels(barchart, show_val = TRUE)
barchart <- chart_labels_text( barchart,
  values = fp_text_settings )
```
