### ISSUE TITLE
outEnd data labels on a chart passed to as_bar_stack() do not populate in powerpoint

### ISSUE THREAD

**Issue by bengowan** [ardata-fr/mschart#21]
Hello,

This is a minor issue I noticed, just thought I would pass along. 

If I send a bar chart with outEnd data labels to the as_bar_stack, the slide doesn't populate in the produced pptx. Changing to an internal data label works fine. Here is an example:

``` r
library(tidyverse)
library(mschart)
library(officer)


dat <- mtcars %>% 
  group_by(am, cyl) %>%
  summarise(disp = mean(disp))


bar_to_stack_outend <- ms_barchart(data = dat, x = "cyl", y = "disp", group = "am") %>% 
                chart_data_labels(show_val = TRUE, position = "outEnd") %>% 
                as_bar_stack()

bar_to_stack_ctr <- ms_barchart(data = dat, x = "cyl", y = "disp", group = "am") %>% 
  chart_data_labels(show_val = TRUE, position = "ctr") %>% 
  as_bar_stack()


doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme") %>% ph_with_chart(chart = bar_to_stack_outend)
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme") %>% ph_with_chart( chart = bar_to_stack_ctr)


print(doc, target = "example.pptx")

```

The first slide chart will fail inside PowerPoint (be blank), but the second will populate OK. 

Thanks for such a fantastic tool as mschart, really appreciate it. 

Cheers,
Ben

**Comment by davidgohel** [comment]
Thanks, 

This run with an (expected) error on my side.

```
Erreur : label position issue with grouping 'clustered'.Arg. position in chart_data_labels() should match one of 'ctr', 'inBase', 'inEnd'.
```

Could you add your `sessionInfo()` please? The actual version is `0.2.2`.

**Comment by bengowan** [comment]
ah yes, sorry, working with mschart_0.2.2.0004, but I am behind on my R ver.

> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mschart_0.2.2.0004 officer_0.2.1      Hmisc_4.1-1        Formula_1.2-2      survival_2.41-3    lattice_0.20-35    rlang_0.1.6       
 [8] bindrcpp_0.2       sjPlot_2.4.0       janitor_0.4.0.9000 lubridate_1.7.1    forcats_0.2.0      stringr_1.2.0      dplyr_0.7.4       
[15] purrr_0.2.4        readr_1.1.1        tidyr_0.7.2        tibble_1.4.2       ggplot2_2.2.1      tidyverse_1.2.1

**Comment by davidgohel** [comment]
you can update from cran.

The latest version will raise an error if you are using values not supported by office.

**Comment by bengowan** [comment]
ok great, thanks so much. 

mschart is so great, thanks again!
