### ISSUE TITLE
Barchart categories being reordered

### ISSUE THREAD

**Issue by bmewing** [ardata-fr/mschart#24]
I'm trying to make a barchart of average values in response to a question. I have three columns, `question`, `mean` and `group`. My data has my questions ordered correctly (though they are duplicated because of the group column. `mschart` sorts the questions in alphabetical order (and when I flip the barchart horizontal, in reverse alphabetical order). There doesn't seem to be a way to force the ordering of groups - is this intentional or is it an enhancement that could be made?

    tmpdt = structure(list(question = c("I1_question", 
    "A1_question", 
    "M1_question", 
    "I2_question", 
    "O1_question", 
    "O2_question", 
    "M2_question", 
    "W1_question", 
    "I3_question", 
    "A2_question", 
    "M3_question", 
    "I4_question", 
    "O3_question", 
    "O4_question", 
    "M4_question", 
    "W2_question"
    ), mean = c(4.17283950617284, 3.69230769230769, 4.01234567901235, 
    3.83333333333333, 3.30434782608696, 3.33783783783784, 3.82716049382716, 
    3.25161290322581, 4.12121212121212, 3.65625, 3.93939393939394, 
    3.90909090909091, 3.16, 3.09677419354839, 3.87878787878788, 2.8125
    ), group = c("Total", "Total", "Total", "Total", "Total", "Total", 
    "Total", "Total", "This Group", "This Group", 
    "This Group", "This Group", "This Group", 
    "This Group", "This Group", "This Group"
    )), .Names = c("question", "mean", "group"), row.names = c(NA, 
    -16L), class = "data.frame")
    
    linec = ms_barchart(data = tmpdt,x="question",y="mean",group="group")

**Comment by davidgohel** [comment]
Hi,

That's because your values should be expressed as factor. Below an illustration:


``` 
# I choose this ordering (that should not be reordered in reverse alphabetical order)

levels <- c("I1_question", "I2_question", 
                         "A1_question", "W2_question", "M1_question", 
                         "M2_question", "W1_question", "I3_question",
                         "O1_question", "O2_question",  
                         "A2_question", "M3_question", "I4_question", "O3_question", "O4_question", 
                         "M4_question")

tmpdt = structure(list(c = c("I1_question", 
                                    "A1_question", 
                                    "M1_question", 
                                    "I2_question", 
                                    "O1_question", 
                                    "O2_question", 
                                    "M2_question", 
                                    "W1_question", 
                                    "I3_question", 
                                    "A2_question", 
                                    "M3_question", 
                                    "I4_question", 
                                    "O3_question", 
                                    "O4_question", 
                                    "M4_question", 
                                    "W2_question"
), mean = c(4.17283950617284, 3.69230769230769, 4.01234567901235, 
            3.83333333333333, 3.30434782608696, 3.33783783783784, 3.82716049382716, 
            3.25161290322581, 4.12121212121212, 3.65625, 3.93939393939394, 
            3.90909090909091, 3.16, 3.09677419354839, 3.87878787878788, 2.8125
), group = c("Total", "Total", "Total", "Total", "Total", "Total", 
             "Total", "Total", "This Group", "This Group", 
             "This Group", "This Group", "This Group", 
             "This Group", "This Group", "This Group"
)), .Names = c("question", "mean", "group"), row.names = c(NA, 
                                                           -16L), class = "data.frame")
tmpdt$question <- factor(tmpdt$question, levels = levels )

linec = ms_barchart(data = tmpdt,x="question",y="mean",group="group")
print(linec, preview = TRUE)
```
