### ISSUE TITLE
Option to turn off line smoothing (feature request)

### ISSUE THREAD

**Issue by persephonet** [ardata-fr/mschart#25]
Hi,

I am trying to recreate a chart that was made natively in powerpoint. The mschart function automatically sets Smoothed line to true (under "Format Data Series -> Fill & Line -> Line -> Smoothed line" in powerpoint). I have tried to fiddle around with the "ms_linechart" object but have been unsuccessful in my attempt to change that option to false because I cannot figure out what the option should be called. I'd appreciate if the feature could be added. 

Additionally, if you could point me towards what you are using to figure out exactly what each argument should be called when the charts are put in powerpoint I would really appreciate it. That way I can contribute next time instead of needing to make an issue.

Thank you,
Persephone

**Comment by davidgohel** [comment]
> I am trying to recreate a chart that was made natively in powerpoint. 

Can you add a image showing what you are trying to do?

It seems @DavidCamposeco replied to this by implementing a feature for specifying smooth lines.

> The mschart function automatically sets Smoothed line to true

I maybe wrong but I don't think it does! Some charts add lines but not smoothed.

> Additionally, if you could point me towards what you are using to figure out exactly what each argument should be called

Yes, agree, a user documentation would be a great ressource but unfortunately I did not find time yet to write it :)

**Comment by c-whelan** [comment]
Is @DavidCamposeco 's feature in the CRAN version yet? I updated the package (0.2.3) but do not see it? I do see the new documentation in the vignette on GitHub. 

Regarding @persephonet 's comment, right now I get smoothed series by default. I also find that changing scatterstyle in the scatterchart `chart_settings()` does not change whether the lines are smoothed or not:

```
library(mschart)
library(tidyverse)

#Produces smoothed lines
ms_linechart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  print(preview = TRUE)

#Produces smoothed lines with markers
ms_scatterchart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  print(preview = TRUE)

#Produces smoothed lines with no markers
ms_scatterchart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  chart_settings(scatterstyle="line") %>%
  print(preview = TRUE)

#Produces smoothed lines with markers
ms_scatterchart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  chart_settings(scatterstyle="lineMarker") %>%
  print(preview = TRUE)

#Produces smoothed lines with no markers
ms_scatterchart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  chart_settings(scatterstyle="smooth") %>%
  print(preview = TRUE)

#Produces smoothed lines with markers
ms_scatterchart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  chart_settings(scatterstyle="smoothMarker") %>%
  print(preview = TRUE)
```

Thanks!
