### ISSUE TITLE
No support for Pie chart

### ISSUE THREAD

**Issue by princecena** [ardata-fr/mschart#28]
There is no support for a pie chart in this package.

**Comment by davidgohel** [comment]
Thanks for your comment

You are right, this is not implemented nor documented: https://ardata-fr.github.io/mschart/articles/introduction.html#available-charts

**Comment by princecena** [comment]
Hi David,

I was looking for native pie chart options in mschart. Are you planning to include the same in the package?

Regards
Prince

**Comment by davidgohel** [comment]
Hello

I can implement it but it's not in the top priorities list :/ Maybe later this year!

**Comment by princecena** [comment]
Hi David,

Sorry to bother you. It would be great if you can provide the support for pie chart.
We replaced our code written earlier in ReporteRs using officer library.
We had few pie charts build in our report which we want to make using officer.

Regards
Prince
