### ISSUE TITLE
No option of selecting a color scheme available in PowerPoint

### ISSUE THREAD

**Issue by princecena** [ardata-fr/mschart#29]
There is no option/command available to select the style/themes/color schemes available in PowerPoint template.
If we have selected the master different from Office, be default, it should use the color schemes of that master in the charts, not the default Office theme.

**Comment by davidgohel** [comment]
Thanks for your comment. 

Yes, there is no option for that. 

> not the default Office theme.

It does not use default office theme but defaults defined in the package that can be changed with R commands.
