### ISSUE TITLE
Cannot colour bars based on conditional formatting

### ISSUE THREAD

**Issue by nathaneastwood** [ardata-fr/mschart#30]
A feature enhancement that would be really useful is to colour bars based on conditional formatting. For example, let's say we have some data:

```
my_data <- data.frame(
  x = c("p_1", "p_2", "p_3"),
  score = c(1, 2, 3),
  training = c(FALSE, FALSE, TRUE)
)
```

I want to generate a bar chart of the scores, but I want to colour the bars for people with training in green and the bars for people without training in red. This isn't currently possible.

**Comment by nathaneastwood** [comment]
I figured out you can do this with a stacked barchart...

```
my_data %>% 
  ms_barchart(x = "x", y = "score", group = "training") %>% 
  as_bar_stack()
```

**Comment by ashishnelson94** [comment]
Hi Nathaniel ,

I am using this package called MS Charts in R where I want to build a horizontal bar chart but I need conditional formatting where the bar comprising of the least measurement should be surrounded with an orange border.

My Dataframe used for the chart looks like this

![image](https://user-images.githubusercontent.com/10890679/52694073-913bfd00-2f8e-11e9-808c-c474858e233a.png)

and the chart I require looks like the screenshot below : 
![image](https://user-images.githubusercontent.com/10890679/52694120-b29ce900-2f8e-11e9-9726-d08ef79cb967.png)

I would extremely grateful if you could assist me on how to proceed on it.

Thanks and Regards,
Ashish
