### ISSUE TITLE
Print no axis label

### ISSUE THREAD

**Issue by bcondron** [ardata-fr/mschart#33]
Is there a way to avoid printing an axis label on a chart? I've managed to get rid of the legend, but I have an x-axis label that I can't seem to get rid of. I still want to use the y-axis label, or I'd just set the font size of axis labels to 0. Any ideas?

**Comment by davidgohel** [comment]
Could you add a reproducible exemple?

**Comment by bcondron** [comment]
Of course! Thanks for coming back so fast! 

data(iris)

```
library(mschart)
library(magrittr)
iris %>%
  ms_linechart(data = ., x = "Species", y = "Petal.Length") %>%
  print( preview = T)
```

produces the following
![image](https://user-images.githubusercontent.com/6919123/46200079-09918100-c354-11e8-9ea2-93fe3c5ddd7c.png)

I want to get rid of the bit I've boxed in the screenshot.

I've tried using:

`chart_labels(xlab = "")`

but while that doesn't print anything there, it still takes up the space (if that makes sense. The chart doesn't adjust to fill the space like it does if you delete the xlabel in the example.)

**Comment by davidgohel** [comment]
I still can see an issue with the title but the x and y labels should now behave as expected (you need to install the latest gh version):

```
library(mschart)
library(officer)
library(magrittr)

ms_linechart(data = iris, 
             x = "Petal.Width", y = "Petal.Length") %>%
  chart_labels(xlab = NULL, ylab = NULL) %>% 
  chart_theme(legend_position = "n") %>% 
  print( preview = TRUE)
```

**Comment by bcondron** [comment]
Thanks David! You're amazing.

What are the steps for getting the current development version into CRAN? Is there anything that I can do to help?

**Comment by davidgohel** [comment]
Thanks.

Well I just found out there is an issue with `ms_areachart`, I'd like to fix it before submission... but I don't know when I will find time for that :)

**Comment by davidgohel** [comment]
I am closing that issue as it is solved now
