### ISSUE TITLE
chart_data_line_width works on scatter charts but not line charts

### ISSUE THREAD

**Issue by bcondron** [ardata-fr/mschart#34]
The following code is taken from the documentation and modified to use ms_linechart instead of ms_scatterchart.

```
my_scatter <- ms_linechart(data = iris, x = "Sepal.Length",
y = "Sepal.Width", group = "Species")
# my_scatter <- chart_settings(my_scatter, scatterstyle = "lineMarker")
my_scatter <- chart_data_fill(my_scatter,
values = c(virginica = "#6FA2FF", versicolor = "#FF6161", setosa = "#81FF5B") )
my_scatter <- chart_data_stroke(my_scatter,
values = c(virginica = "black", versicolor = "black", setosa = "black") )
my_scatter <- chart_data_symbol(my_scatter,
values = c(virginica = "circle", versicolor = "diamond", setosa = "circle") )
my_scatter <- chart_data_size(my_scatter,
values = c(virginica = 20, versicolor = 16, setosa = 20) )
my_scatter <- chart_data_line_width(my_scatter,
values = c(virginica = 2, versicolor = 3, setosa = 6) ) %>% print (preview = T)
```

The line width in the resulting graphic is defaulting to 3.75 on my machine (using the cran version of the repo) despite having been declared above. Note that when using a scatter plot instead of a line chart, chart_data_line_width works perfectly.

**Comment by davidgohel** [comment]
thanks

**Comment by bcondron** [comment]
Dude, you're amazing.

I know maintaining a package like this is a pretty thankless job, but seriously thank you.

**Comment by davidgohel** [comment]
thanks :)

This one is not easy to maintain, as it get more audience, I will need to improve tests and documentation...
