### ISSUE TITLE
Create more complex charts with subtitles and footers

### ISSUE THREAD

**Issue by gjungb** [ardata-fr/mschart#37]
Hi, we are working on an automated reporting tool to generate hundreds of MS Word documents. The documents contain a bunch of graphics like the following one:

<img width="530" alt="customized_chart_engawa" src="https://user-images.githubusercontent.com/3391068/47419669-fa4bfa80-d77c-11e8-956d-7742b286c24a.png">

Do you see any chance to achieve this with mschart? Especially:

- subtitle(s)
- footer

**Comment by davidgohel** [comment]
I think it is better to use ggplot2 or base graphics. mschart is a tool to let readers with no R skills to customize their plot in office. If you want to produce sophisticated graphics, you will be happier with a complete graphic API made for that.
