### ISSUE TITLE
method to easily view a ms_chart object

### ISSUE THREAD

**Issue by npelikan** [ardata-fr/mschart#4]
When a presentation is being designed, analysts often like to view edits to graphs in their IDE, rather than having to generate a whole presentation to confirm each edit. To this end I believe that a view method for ms_charts would be really helpful. Something like in ggplot2, where calling a ggplot2 object by default plots it.

Ideal behavior would be to create and display a blank temporary ppt document, similarly to the below convenience function we've been using:

```
show_mschart <- function(ch){
  doc <- read_pptx() %>%
    add_slide(layout = "Title and Content", master = "Office Theme") %>%
    ph_with_chart(value = ch)
  print(doc, target = tempfile(fileext = ".pptx")) %>% browseURL()
}
```

**Comment by davidgohel** [comment]
Thanks for the suggestion. I used print method for the implementation:

```
my_barchart <- ms_barchart(data = browser_data,
  x = "browser", y = "value", group = "serie")
print(my_barchart, preview = TRUE)
```

You will need to update the package from github.

**Comment by npelikan** [comment]
Thanks!
