### ISSUE TITLE
Highlighting the bar based on a condition

### ISSUE THREAD

**Issue by ashishnelson94** [ardata-fr/mschart#40]
Hi Daniel ,

I am using this package called MS Charts in R where I want to build a horizontal bar chart but I need conditional formatting where the bar comprising of the least measurement should be surrounded with an orange border.

My Dataframe used for the chart looks like this

![image](https://user-images.githubusercontent.com/10890679/52694073-913bfd00-2f8e-11e9-808c-c474858e233a.png)

and the chart I require looks like the screenshot below : 
![image](https://user-images.githubusercontent.com/10890679/52694120-b29ce900-2f8e-11e9-9726-d08ef79cb967.png)

I would be extremely grateful if you could assist me on how to proceed on it.

Thanks and Regards,
Ashish

**Comment by davidgohel** [comment]
better late than never...

Here is an example that can be adapted to the need

https://ardata-fr.github.io/officeverse/charts-with-mschart.html#custom-labels
