### ISSUE TITLE
Target line in MS Bar chart

### ISSUE THREAD

**Issue by ashishnelson94** [ardata-fr/mschart#42]
Hi All , (@davidgohel @DavidCamposeco @qfazille @clementinejager )

Hope you all doing good.

I needed your help in terms of achieving a requirement received by one of our clients.
We built a bar chart using MS Chart and exported it to a power point via Officers package but the client wants the bar chart to have a thin dotted/dashed target line.
Please find below the chart image for your reference.
![image](https://user-images.githubusercontent.com/10890679/53223667-1bbfe300-3698-11e9-90d4-43beba0ffb21.png)

Do you think it's possible to do it via MS Charts? We read the documentation provided by you and weren't able to find a feature that could help us get this line.
It would be great to have your assistance on it.

Thanks and Regards,
Ashish Nelson

**Comment by qfazille** [comment]
Hi Ashish,

We're glad that you like `mschart` !
Regarding your suggestion, this looks like a **good option to add**.
Unfortunately we are running out of time at the moment, however **any contributions are very welcomed.**

We will let your issue opened for now in case you (or someone else) would come up with a pull request on that topic.

Have a good day,
Quentin

**Comment by ashishnelson94** [comment]
Hey Quentin @qfazille  ,

Thank you so much for getting back to us. Is there a way where you can redirect us to someone who can help me edit this bit in the library itself. The reason being, our clients really need this feature so as to see a few KPI's against its target. It would be really helpful if this small addition could be made.

Thanks a lot for your help.

Regards,
Ashish Nelson

**Comment by davidgohel** [comment]
Hi, 

No sorry. As Quentin told you, we don't have time to work on this for now. Unfortunately, we can't neither provide you a contact that would help you do the work your customer really need. 

This feature does not seem to correspond to anything offered in Office chart (I may be wrong but I don't see any option for that in the office API), I don't think it can be done with mschart. 


KR
David
