### ISSUE TITLE
Is it possible to make the bubbles in ms_scatterchart translucent?

### ISSUE THREAD

**Issue by Madeehab** [ardata-fr/mschart#43]
Hi Team,

Is it possible to make the bubbles(in bubble chart created using ms_scatterchart) translucent?

Please find the below the image to see an eg. 
![image](https://user-images.githubusercontent.com/47552032/55157337-23d0de00-5182-11e9-9801-be5e9240fc1b.png)

Kind Regards,
Madeeha

**Comment by davidgohel** [comment]
yes

KR,
David

**Comment by davidgohel** [comment]
you need to add transparency in the color code: i.e. #6FA2FF55

**Comment by Madeehab** [comment]
This is cool. Thank You :)
