### ISSUE TITLE
Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  :    StartTag: invalid element name [68]

### ISSUE THREAD

**Issue by kshitijpathak** [ardata-fr/mschart#44]
I am trying to make a bar-chart using the following code snippet but I am getting the following 

**error** :-
**Error in doc_parse_raw(x, encoding = encoding, base_url = base_url, as_html = as_html,  :    StartTag: invalid element name [68]**

Please suggest a way to rectify this error.

**code** :- 

summary <- data.frame(TotalAssets = rep(c("<$500k","$500k to $1M","$1M to $2M"
                                          ,"$2M to $5M","$5M to $10M","$10M to $50M","$50M to $100M",">$100M"),3)
                       ,variable = c(rep("client",8),rep("EDF",8),rep("RC",8))
                      ,value = c(rep(1,8),rep(2,8),rep(3,8)))
  my_bar_stack_01 <- ms_barchart(data = summary, x = "TotalAssets",
                                 y = "value", group = "variable")
  my_bar_stack_01 <- as_bar_stack( my_bar_stack_01)
  my_bar_stack_01 <- chart_ax_y(my_bar_stack_01,second_axis = FALSE)
  
  doc <- read_pptx()
  doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
  doc <- ph_with_chart(doc, chart = my_bar_stack_01)
  print(doc, target = "barchart_01_stacked.pptx")

**Comment by filipwastberg** [comment]
I think this has something to do with characters such as `<`. 

I get a similar error when using `&`:
```
library(magrittr)
library(mschart)
library(officer)

dat <- browser_data
dat[dat$browser %in% "Chrome", "browser"] <- "ä& åÅ öÖ"
barchart <- ms_barchart(data = dat, 
                        x = "browser", 
                        y = "value", 
                        group = "serie")
barchart <- chart_labels(barchart, title = "©")
doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
doc <- ph_with_chart(doc, chart = barchart)
print(doc, target = "Presentation.pptx")
```
Sessioninfo:
```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252
[4] LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] officer_0.3.3     mschart_0.2.4.004 magrittr_1.5     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1        packrat_0.5.0     digest_0.6.18     cellranger_1.1.0  R6_2.4.0          zip_2.0.1        
 [7] writexl_1.1       rlang_0.3.4       uuid_0.1-2        data.table_1.12.2 xml2_1.2.0        tools_3.5.3      
[13] compiler_3.5.3    base64enc_0.1-3   htmltools_0.3.6  
```

**Comment by schaffstein** [comment]
I can confirm the problem.
If I replace characters such as `&`, `<`, `>` with their html entities `&amp;`, `&lt;`, `&gt;` I can get the chart to generate.

**Comment by schaffstein** [comment]
Still hoping this will get fixed. For the meantime I created a little workaround.
If you parse your text through the following function, it can handle at least the most common characters.

```
#' sanitises text for the use with package `mschart`
#'
#' @details
#' The texts encoding is set to latin1 and characters causing trouble
#' (currently `&` `<` and `>`) are replaced
#'
#' @param string String. The string to sanitise
#'
#' @return Returns the sanitised string.
#' @export
#'
#' @examples
#' encodeForMschart(string = "Text mit ä, ü und ö sowie &, < und >")
encodeForMschart <- function(string) {
  # convert encoding of all vector elements to utf8
  result <- stringi::stri_encode(string, to = "utf8")
 
  # change encoding to bytes
  # this creates hex-representation (Glück = Gl\xC3\xBCck)
  Encoding(result) <- "bytes"
 
  # change encoding back to latin1 (mschart cannot handle "bytes" encoding)
  # but this keeps hex-representation of special chars in tact
  Encoding(result) <- "latin1"
 
  # now replace characters currently causing trouble
  result <- str_replace_all(result, "&", "&amp;")
  result <- str_replace_all(result, "<", "&lt;")
  result <- str_replace_all(result, ">", "&gt;")
 
  return(result)
}
```
