### ISSUE TITLE
2 charts in one graph

### ISSUE THREAD

**Issue by jemnbuchu** [ardata-fr/mschart#46]
Hi,

Is it possible to have 2 native charts in one plot with same x-axis and different y-axis? I'm trying to combine bar chart and line chart.

**Comment by samimesfin** [comment]
Hello! I am also looking for a solution to add a secondary axis. Is there a way of doing so please?
Thanks

**Comment by davidgohel** [comment]
No sorry, that's not a feature of mschart. Maybe one day but not now
