### ISSUE TITLE
Ability to change border color / remove border on bars barchart

### ISSUE THREAD

**Issue by austinsimeone** [ardata-fr/mschart#51]
Hi! 

Thanks for making an awesome package first off!

Bug / Enhancement

When using chart_data_fill() I am not able to change the color of the barchart border or remove it. There is a thin line around the bars that I can't find a way to remove.

Picture below
![Capture](https://user-images.githubusercontent.com/34195887/73470151-0eea4b80-434d-11ea-8a94-3806e2a9d673.JPG)

**Comment by dakvid** [comment]
You want to also use chart_data_stroke with the same colour. Took me some headscratching, but similar with ggplot etc.

**Comment by davidgohel** [comment]
I will add more decent documentation soon.
