### ISSUE TITLE
More flexible data labels?

### ISSUE THREAD

**Issue by IanWakeling** [ardata-fr/mschart#53]
Thank you for such a wonderful package.

I have a suggestion for what I hope is a simple enhancement.  Would it be possible to have a user supplied vector of strings to use as data labels?  For example

my_chart <- ms_barchart(data=my_data, x="x", y="y", ulabels="mystrings")

and then something like:

chart_data_labels(my_chart, show_ulabels = TRUE)

I am thinking of a statistical application where I would like to print the results of a significance test associated with each bar.  However I think a feature like this would have many other uses.

**Comment by sda030** [comment]
I think it would also offer a simpler way of adjusting number of decimals, allowing an end-user of a wrapper function to decide whether or not to add the percentage sign, etc as I feel the legacy office way of doing things is a bit clunky.

**Comment by davidgohel** [comment]
The feature is now available is the dev version.

To use it, specify which label column to use in argument `labels`.


```
library(officer)
library(mschart)
library(magrittr)
# example chart_01 -------
dat <- browser_data
dat$label1 <- LETTERS[seq_len(nrow(dat))]
dat$label2 <- letters[seq_len(nrow(dat))]
chart_01 <- ms_barchart(data = dat, x = "browser", y = "value", group = "serie", 
                        labels = c("label1", "label2"))
chart_01 <- chart_settings( x = chart_01, dir="vertical",
                            grouping="clustered", gap_width = 50 )
chart_01 <- chart_ax_x( x= chart_01, cross_between = 'between',
                        major_tick_mark="out")
chart_01 <- chart_ax_y( x= chart_01, cross_between = "midCat",
                        major_tick_mark="in")
chart_01 <- chart_data_labels(chart_01, position = "outEnd")

fp_text_settings <- list(
  serie1 = fp_text(font.size = 7, color = "red"),
  serie2 = fp_text(font.size = 0, color = "purple"),
  serie3 = fp_text(font.size = 19, color = "wheat")
)
chart_01 <- chart_labels_text(chart_01, values = fp_text_settings )

read_pptx() %>%
  add_slide() %>%
  ph_with(chart_01, location = ph_location_type()) %>%
  print(tempfile(fileext = ".pptx")) %>% browseURL()
```

<img width="920" alt="Capture d’écran 2021-04-12 à 17 51 21" src="https://user-images.githubusercontent.com/4331618/114423682-b43ab980-9bb7-11eb-977e-0073efcba2c0.png">

**Comment by davidgohel** [comment]
@sda030 you can store and format what you want in a label column and reuse it in the chart
