### ISSUE TITLE
Feature request: Hiding title, y-label and x-label

### ISSUE THREAD

**Issue by sda030** [ardata-fr/mschart#61]
Currently, supplying mschart::chart_labels(title, xlab, ylab) with NULL or NA do not delete them completely. Deleting such titles/labels are sometimes necessary to maximize space for the figure, as title often goes into a separate figure caption anyway. There are xml-tags for hiding title, y-label and x-label. I've been able to post hoc delete the title (deleting part of raw text), but unable to use same trick for the xlab and ylab.

P.S. Grateful for the "fix issue with labels that contains <>&." in update 0.2.6!

**Comment by davidgohel** [comment]
Great, thanks for reporting this - I am working on the package at this moment and will fix that soon

**Comment by sda030** [comment]
Just to clarify myself, if left as blank or "", the labels seem to be blank but are actually there in the plot, just need to click on the right blank space...

**Comment by davidgohel** [comment]
I am trying to reproduce this issue but I can't.

See this code:

```
library(mschart)
mylc <- ms_linechart(data = browser_ts, x = "date", y = "freq",
                     group = "browser")
mylc <- chart_labels(mylc, title = "my title", xlab = "my x label")

print(mylc, preview = TRUE)
```

<img width="897" alt="Capture d’écran 2021-04-12 à 18 06 00" src="https://user-images.githubusercontent.com/4331618/114425848-bf8ee480-9bb9-11eb-9dee-9e0cb9861782.png">

**Can you post a reproducible example?** I may misunderstand what you're reporting.

**Comment by sda030** [comment]
Apologies, I do not understand why but issue is not there anymore. My bad.

**Comment by davidgohel** [comment]
no problem. I had a doubt when I read my code. Feel free to comment here if this happens again (and copy here your code)
