### ISSUE TITLE
Scatterchart with linemarker does not work

### ISSUE THREAD

**Issue by thuyvlu** [ardata-fr/mschart#64]
When creating scattercharts with grouping and linemarker, the colorings are correct, but the lines don't show. From the powerpoint created, it says that the type of chart is scatter with lines and markers but the lines still don't show even when we manually change chart type to scatter with lines. It'd be great if this can be looked into. Thank you!

Example: 
```
library(tidyverse)
library(mschart)
library(officer)

data <-
 data.frame(
  y = c(1, 5, 2, 9),
  x = c(1, 3, 4, 10),
  color = c("red", "blue", "red", "blue")
 )

chart <-
 ms_scatterchart(data = data,
                 x = "x",
                 y = "y",
                 group = "color") %>%
 chart_settings(style = "lineMarker")

pptx_obj <- read_pptx() %>%
 add_slide(layout = "Title and Content", master = "Office Theme") %>%
 ph_with(value = chart, location = ph_location_type(type = "body")) %>%
 print(target = "example.pptx")
```

The chart created:

![image](https://user-images.githubusercontent.com/72517072/131420764-3124c1a7-383a-40b4-8e03-598b2969ed29.png)

**Comment by davidgohel** [comment]
I suppose you are not using github version. Could you please update your package with github version?

**Comment by thuyvlu** [comment]
You were correct! Updating the package with github version resolves the issue. Thank you! 

I have some follow up questions if you don't mind. I can create another issue if necessary. 

It seems like the style "lineMarker" and "smoothMarker" have the same effect. I used "lineMarker" and was expecting that it would produce straight lines connecting the markers, but the lines are smooth. The markers are also connected according to the order of the y values instead of the x values as can be seen in the below example. Is there an option that we can choose how we want the markers to be connect?

I appreciate your attention to this. Thanks again!

Example:
```
library(tidyverse)
library(mschart)
library(officer)

data <-
 data.frame(
  y = c(1, 5, 2, 9, 7.5, 6, 8, 1, 3, 7),
  x = c(1, 3, 4, 5.5, 6, 1, 3, 4, 5.5, 6),
  color = c(rep("red", 5), rep("blue", 5))
 )

chart <-
 ms_scatterchart(data = data,
                 x = "x",
                 y = "y",
                 group = "color") %>%
 chart_settings(style = "lineMarker")


pptx_obj <- read_pptx() %>%
 add_slide(layout = "Title and Content", master = "Office Theme") %>%
 ph_with(value = chart, location = ph_location_type(type = "body")) %>%
 print(target = "example_linemarker.pptx")
```

The chart created:

![image](https://user-images.githubusercontent.com/72517072/131541271-5194e391-173b-44e4-80fa-b89878dbb87c.png)
