### ISSUE TITLE
scatterplot leader lines

### ISSUE THREAD

**Issue by nick-moffitt** [ardata-fr/mschart#69]
When creating scatterplots, I love the chart_labels_text() function to add labels over points. Sometimes the labels are really close to each other, and if I space them out manually, no leader lines appear like they would in a default Microsoft chart. Is there functionality for leader lines in mschart or is there a plan to add that if not?

**Comment by davidgohel** [comment]
>  Is there functionality for leader lines in mschart or is there a plan to add that if not?

Sorry, no
