### ISSUE TITLE
Nested barchart

### ISSUE THREAD

**Issue by sda030** [ardata-fr/mschart#75]
I struggly to figure out how to make a clustered stacked barchart, such as [these from Google](https://www.google.com/search?q=excel+clustered+stacked+bar+chart&tbm=isch&ved=2ahUKEwiC_ezGs4v7AhXZGHcKHT0MB7kQ2-cCegQIABAA&oq=excel+clustered+stacked+bar+chart&gs_lcp=CgNpbWcQAzIFCAAQgAQyBwgAEIAEEBg6BAgAEB5QgwVYxzFg0DNoAHAAeACAAYABiAGRC5IBBDIxLjGYAQCgAQGqAQtnd3Mtd2l6LWltZ8ABAQ&sclient=img&ei=3zxgY8KRJtmx3AO9mJzICw&bih=793&biw=1707&rlz=1C1GCEU_enNO1000NO1000). 

The group-argument would be used for the series. There would need to be another new argument to specify clustering (or facetting, using ggplot2 terminology)?

**Comment by davidgohel** [comment]
From what I saw on your examples, all drive to tweaking graph by faking an additional dimension. We can't really do that (or we can't dedicate the time it would require to get that feature).
