### ISSUE TITLE
Adding images as axis labels?

### ISSUE THREAD

**Issue by npelikan** [ardata-fr/mschart#8]
Hi David,

Is it possible to add the ability to use images as axis labels? That would be a huge boon to usability for some of our client teams.

Thanks!

**Comment by davidgohel** [comment]
Hi Nick

Do you have an example? I am not sure it can be done with ms charts...

**Comment by npelikan** [comment]
Hi David,

Further discussion with the requester revealed there's no native-pptx way to add the axis label images, they're pasted in manually as separate objects and dragged to cover the axis labels. I don't think there's any way to do this using mschart. Thanks!
