### ISSUE TITLE
Barchart axis in reverse order

### ISSUE THREAD

**Issue by datastoriesbyKat** [ardata-fr/mschart#93]
hello I'm trying to make a side by side bar representing disgree facing left and agree facing right barchart. Currently I can only do it manually within PPT. I would like to know a way how to do that in R since I'm using mschart to generate my report.
![2bars](https://github.com/ardata-fr/mschart/assets/144898931/8ace0c31-10ff-4e39-8cb4-c7062f9d22b0)

**Comment by eli-daniels** [comment]
Hi @datastoriesbyKat,
Hopefully the following is still relevant to you. Here is a reprex that show how to do this.

Important parts are that: 
1. disagree values are negative
2. chart_settings sets grouping to stacked for a stacked bar chart
3. chart_settings sets overlap to 100 for 100% overlap, otherwise they are offset.

```
# Create example data
x <- data.frame(
  Question = c("A", "B"),
  Agree = c(80, 35),
  Disagree = c(-20, -65) # Important for disagree values to be negative !
  )

# Restructure to longer data
x <- tidyr::pivot_longer(
  x,
  c(Agree, Disagree),
  names_to = 'response',
  values_to =  'perc')

# Using the example from github page
library(mschart)
bar <-
  ms_barchart(
    data = x, x = 'Question', y = "perc", group = "response"
  )

# Important to set grouping to stacked and overlap 100
bar <- chart_settings(bar, grouping = "stacked", dir = "horizontal", overlap = 100)

# Then use package officer to send the object as a chart.

library(officer)
doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
doc <- ph_with(doc, value = bar, location = ph_location_fullsize())

print(doc, target = "example.pptx")
browseURL('example.pptx')

```
